version: '3.8'

services:
  mongodb:
    image: mongo:7.0-jammy
    container_name: aarambha_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: aarambha_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
    driver: local
