/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        sans: ['"Poppins"', '"Inter"', '-apple-system', 'sans-serif'],
        script: ['"Caveat"', '"Dancing Script"', 'cursive'],
        heading: ['"Playfair Display"', 'Georgia', 'serif'],
      },
      colors: {
        ivory: '#FCFAF6',
        sand: '#EDE2D0',
        peach: '#E8B9A5',
        apricot: '#F2C6A0',
        sage: '#C8D8C0',
        taupe: '#756B63',
        cocoa: '#493B34',
        gold: '#D8B77A',
        terracotta: {
          DEFAULT: '#C65A2E',
          hover: '#B24E25',
          light: '#F8EFEA',
        },
        ramp: {
          primary: '#C65A2E',
          navy: '#493B34',
          charcoal: '#2D1F18',
          cta: '#C65A2E',
          'cta-hover': '#B24E25',
          'blue-light': '#E8B9A5',
          'blue-pale': '#EDE2D0',
          surface: '#FCFAF6',
          'surface-subtle': '#F8EFEA',
          border: '#EDE2D0',
          stone: '#756B63',
          slate: '#756B63',
        },
        primary: {
          DEFAULT: '#C65A2E',
          hover: '#B24E25',
          light: '#E8B9A5',
          pale: '#F8EFEA',
          dark: '#493B34',
        },
        secondary: {
          DEFAULT: '#493B34',
          hover: '#2D1F18',
          light: '#756B63',
        },
        cta: {
          DEFAULT: '#C65A2E',
          hover: '#B24E25',
          active: '#9E431E',
          text: '#FFFFFF',
        },
        charcoal: '#2D1F18',
        surface: {
          DEFAULT: '#FCFAF6',
          subtle: '#F8EFEA',
          border: '#EDE2D0',
        },
      },
      borderRadius: {
        'btn': '8px',
        'input': '10px',
        'card': '14px',
        'badge': '6px',
        'md': '10px',
        'lg': '14px',
        'xl': '18px',
        '2xl': '22px',
      },
      boxShadow: {
        'subtle': 'rgba(73, 59, 52, 0.04) 0px 1px 3px',
        'card-hover': 'rgba(73, 59, 52, 0.08) 0px 4px 12px',
        'btn-hover': 'rgba(198, 90, 46, 0.2) 0px 2px 6px',
        'cta-glow': 'rgba(198, 90, 46, 0.2) 0px 8px 24px',
        'dropdown': 'rgba(73, 59, 52, 0.1) 0px 10px 30px 0px, rgba(73, 59, 52, 0.05) 0px 1px 3px 0px',
        'focus-ring': '0px 0px 0px 3px rgba(198, 90, 46, 0.2)',
      },
      spacing: {
        '4.5': '18px',
        '15': '60px',
      },
    },
  },
  plugins: [],
};
