export const colors = {
  primary: '#C65A2E',
  secondary: '#493B34',
  surface: '#FCFAF6',
  'on-surface': '#493B34',
  'primary-interactive': '#C65A2E',
  'surface-dark': '#2D1F18',
  'surface-darker': '#1A120E',
  'accent-soft': '#E8B9A5',
  'accent-light': '#F8EFEA',
  'text-primary': '#493B34',
  'text-inverse': '#FCFAF6',
  'text-tertiary': '#756B63',
  'border-subtle': '#EDE2D0',
  'border-muted': '#F8EFEA',
  // Backward compatibility mappings
  espresso: '#2D1F18',
  'espresso-dark': '#1A120E',
  terracotta: '#C65A2E',
  'terracotta-dark': '#B24E25',
  sand: '#EDE2D0',
  'sand-light': '#F8EFEA',
  cream: '#FCFAF6',
};
