export const colors = {
  primary: '#AFB2CE',
  secondary: '#9CB4E8',
  surface: '#000000',
  'on-surface': '#FFFFFF',
  'primary-interactive': '#5266EB',
  'surface-dark': '#171721',
  'surface-darker': '#272735',
  'accent-soft': '#AFB2CE',
  'accent-light': '#EDEDF3',
  'text-primary': '#000000',
  'text-inverse': '#EDEDF3',
  'text-tertiary': '#C3C3CC',
  'border-subtle': '#EBEBEB',
  'border-muted': '#F5F5F5',
  // Backward compatibility mappings
  espresso: '#171721',
  'espresso-dark': '#000000',
  terracotta: '#5266EB',
  'terracotta-dark': '#3E51D4',
  sand: '#AFB2CE',
  'sand-light': '#EDEDF3',
  cream: '#FFFFFF',
};

